use crypto_bigint::subtle::{Choice, CtOption};
use k256::{EncodedPoint, ProjectivePoint, PublicKey, Scalar, elliptic_curve::{Field, sec1::{FromEncodedPoint, ToEncodedPoint}}};
use rand_core::OsRng;
use tokio::{io::{AsyncReadExt, AsyncWriteExt, BufReader}, net::tcp::{OwnedReadHalf, OwnedWriteHalf}};

/// A `Verifier` participates in a Schnorr identification protocol.
///
/// # Overview
/// The `Verifier` is responsible for checking the prover's knowledge of the secret key
/// corresponding to a public key. It interacts with the prover by:
/// 1. Receiving the **commitment** `rG`
/// 2. Generating a **challenge** `c`
/// 3. Verifying the prover's **response** `zG = rG + c*PK`
///
/// The `Verifier` maintains internal state for one round of the interactive protocol.
pub struct Verifier {
    /// The public key of the prover being verified.
    pub public_key: PublicKey,  
    
    /// The commitment sent by the prover.
    /// This is `rG`, where `r` is the prover's secret random scalar.
    pub commitment: CtOption<ProjectivePoint>,  
    
    /// The challenge scalar `c` generated by the verifier.
    /// Sent to the prover to elicit a response proving knowledge of the secret key.
    pub challenge: Option<Scalar>,     
    
    /// The prover's response to the challenge.
    /// Typically `zG = rG + c*PK`.
    pub response: CtOption<ProjectivePoint>
}

impl Verifier {
    pub fn new(pk: PublicKey) -> Self {
        Verifier { 
            public_key: pk, 
            commitment: CtOption::new(ProjectivePoint::IDENTITY, Choice::from(0)), 
            challenge: None,
            response: CtOption::new(ProjectivePoint::IDENTITY, Choice::from(0)), 
 }
    }
    pub async fn send_challenge(&mut self, writer: &mut OwnedWriteHalf) -> anyhow::Result<()> {
        let c = Scalar::random(&mut OsRng);
        self.challenge = Some(c);
        writer.write_all(&c.to_bytes()).await?;
        Ok(())
    }
pub async fn read_point(&self, reader: &mut BufReader<OwnedReadHalf>) -> anyhow::Result<CtOption<ProjectivePoint>> {
    let mut buf = [0u8; 65];
    reader.read_exact(&mut buf).await?;

    let encoded = EncodedPoint::from_bytes(&buf)?;
    let point = ProjectivePoint::from_encoded_point(&encoded);

    Ok(point)
}
    pub async fn read_commitment(&mut self, reader: &mut BufReader<OwnedReadHalf>) -> anyhow::Result<()> {
        let commit = self.read_point(reader).await?;
        self.commitment = commit;
        //println!("received {:?}", commit);
        Ok(())
    }
    pub async fn verify(&self,reader: &mut BufReader<OwnedReadHalf>,writer: &mut OwnedWriteHalf)->anyhow::Result<bool> {
        let response = self.read_point(reader).await?;
        let c = self.challenge.unwrap();
        let pk  = ProjectivePoint::from_encoded_point(
            &self.public_key.to_encoded_point(false)).unwrap();
        let u = pk *c;
        let commit = self.commitment.unwrap();
        if commit+u==response.unwrap() {
            writer.write(b"Verification ok. User identified!").await?;
            Ok(true)
        } else {
            writer.write(b"Verification fails. User not identified!").await?;
            Ok(false)
        }
  
    }
}